# Generated by Django 3.2.3 on 2021-07-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210721_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsmodel',
            old_name='user',
            new_name='userRater',
        ),
    ]
