# Generated by Django 3.2.3 on 2021-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_barberaservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceCategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='servicePrice',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
