# Generated by Django 3.2.3 on 2021-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210726_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberaservices',
            name='seviceName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceID',
            field=models.CharField(default='BMH01', max_length=50),
        ),
    ]
