# Generated by Django 3.2.3 on 2021-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210726_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberaservices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='barberaservices',
            name='serviceID',
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='ServiceID',
            field=models.AutoField(db_column='BID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
