# Generated by Django 3.2.3 on 2021-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210726_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberaservices',
            name='ServiceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
