# Generated by Django 3.2.3 on 2021-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210726_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barberaservices',
            old_name='servicePrice',
            new_name='serviceCategoryDiscount',
        ),
        migrations.RenameField(
            model_name='barberaservices',
            old_name='serviceCategory',
            new_name='serviceSubCategory1',
        ),
        migrations.RenameField(
            model_name='barberaservices',
            old_name='serviceSubCategory',
            new_name='serviceSubCategory2',
        ),
        migrations.RemoveField(
            model_name='barberaservices',
            name='serviceDesc',
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory1Desc',
            field=models.CharField(default='Barbera', max_length=300),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory1Discount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory1Price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory2Desc',
            field=models.CharField(default='Barbera', max_length=300),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory2Discount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory2Price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory3Desc',
            field=models.CharField(default='Barbera', max_length=300),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory3Discount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='barberaservices',
            name='serviceSubCategory3Price',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
