# Generated by Django 3.2.3 on 2021-08-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210812_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barberaservices',
            old_name='serviceCategory1Discount',
            new_name='serviceCategoryDiscount',
        ),
    ]
