# Generated by Django 3.2.3 on 2021-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_servicecategory1discount_barberaservices_servicecategorydiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceCategoryDiscount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory1Price',
            field=models.IntegerField(default='0'),
        ),
    ]
