# Generated by Django 3.2.3 on 2021-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210817_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory1Discount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory2Discount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory2Price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory3Discount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceSubCategory3Price',
            field=models.IntegerField(default='0'),
        ),
    ]
