# Generated by Django 3.2.3 on 2021-08-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210821_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberaservices',
            name='serviceCategory',
        ),
    ]
