# Generated by Django 3.2.3 on 2021-08-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_barberaservices_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberaservices',
            name='serviceCategory',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('wedding', 'wedding'), ('kids', 'kids')], default='men', max_length=50),
        ),
    ]
