# Generated by Django 3.2.3 on 2021-08-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_barberaservices_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberaservices',
            name='serviceCategory',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Wedding', 'wedding'), ('Kids', 'kids')], default='men', max_length=50),
        ),
    ]
